from typing import List, Dict, Any, TypedDict, Annotated, Union
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from ..models.schemas import Source

class AgentState(TypedDict):
    # The history of messages in the conversation
    messages: Annotated[List[BaseMessage], add_messages]
    # The user's original query
    query: str
    # The plan generated by the agent
    plan: List[str]
    # Collected context from retrieval
    context: List[Dict[str, Any]]
    # Intermediate steps/reasoning
    intermediate_steps: List[str]
    # Sources used for the final answer
    sources: List[Source]
    # Prediction of confidence
    confidence: float
    # The final grounded answer
    answer: str
    # Success/Failure flags
    should_retry: bool
    errors: List[str]
